### ISSUE TITLE
testing environment using dev containers

### ISSUE THREAD

**Issue by jecluis** [ceph/bubbles#1]
While developing, we need to ensure our work is easily testable using several VMs deploying Ceph with containers and orchestrated by cephadm.

While this would be trivial by consuming containers from quay, we need to take into account that we are developing a ceph-mgr module here and that's the bit that is important to test in this scenario. I.e., we need to ensure we have this module in the containers so we can actually test it.

There must be a way to create containers based off of one's development tree, locally, that can be consumed by cephadm running on the VMs.

**Comment by jmolmo** [comment]
I would like to suggest to take a look to the dev. environment used by some of us in the cephadm development. (I even use it with plan modification for rook orchestrator dev. in a k8s lab)
https://docs.ceph.com/en/latest/dev/cephadm/developing-cephadm/#kcli-a-virtualization-management-tool-to-make-easy-orchestrators-development

Using basically the same tool we have also created a test integration framework:
https://github.com/ceph/ceph/tree/master/src/test/behave_tests

**Comment by jecluis** [comment]
Nice! Good shout. Will take a look. Thanks :)
